apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-{{ .Release.Name }}
  labels:
    {{- include "spring-boot-helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}