replicaCount: 1

image:
  repository: "registry.digitalocean.com/curamet/hello-world-java-demo"
  tag: "v1"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 8080

service:
  name: spring-boot-helloworld
  type: LoadBalancer
  port: 8080
