replicaCount: 2

image:
  repository: "registry.digitalocean.com/curamet/spring-boot-api-demo"
  tag: "latest"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 8080

service:
  name: spring-boot-helloworld
  type: LoadBalancer
  port: 8081