name: CI/CD Branch Verify Pipeline

on:
  push:
    branches-ignore:
      - master
jobs:
  BRANCH-VERIFY:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set vars outputs
      id: vars
      run: |
         echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         echo "CURRENT_TIMESTAMP=$(date +'%Y-%m-%dT%H%M%SZ')" >> $GITHUB_OUTPUT

    - name: Verify with Maven
      run: mvn clean verify

    - name: Package with Maven
      run: mvn clean package -Dmaven.test.skip
